name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
      releaseBranch:
        description: 'Release branch'
        required: true
        default: 'release'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Do a full checkout (all branches)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: milliHQ/gh-action-release-branch@v2.0.0
        with:
          release-branch: ${{ github.event.inputs.releaseBranch }}
          release-tag: ${{ github.event.inputs.tag }}
          exclude: |
            .vscode/**/*
            packages/**/*
            test/**/*
            docker-compose.yml
            jest.config.js
            package.json
            tsconfig.json
            yarn.lock
